// <auto-generated />
namespace MagazaSistem.Entites.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class database6 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(database6));
        
        string IMigrationMetadata.Id
        {
            get { return "202206021314035_database6"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
