// <auto-generated />
namespace MagazaSistem.Entites.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class database9 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(database9));
        
        string IMigrationMetadata.Id
        {
            get { return "202206142141510_database9"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
